# Generated by Django 4.0.2 on 2022-03-12 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('wait_time', models.IntegerField()),
                ('price', models.FloatField()),
                ('allow_wait', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=1024)),
                ('zone', models.CharField(choices=[('Zona libre', 'La plaza está situada en una zona libre'), ('Zona Azul', 'La plaza está situada en zona azul'), ('Zona Verde', 'La plaza está situada en zona verde'), ('Zona Roja', 'La plaza está situada en zona roja'), ('Zona Naranja', 'La plaza está situada en zona naranja')], default='Zona libre', max_length=256)),
                ('limited_mobility', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Initial', 'Estado inicial'), ('Arrival', 'Estado llegada'), ('Departure', 'Estado salida'), ('Rating', 'Estado valoración')], default='Initial', max_length=256)),
                ('observation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(choices=[(1, 'Muy mala'), (2, 'Mala'), (3, 'Regular'), (4, 'Buena'), (5, 'Muy Buena')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('n_extend', models.IntegerField()),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=400)),
                ('license_plate', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Segmento A', 'El vehículo pertenece al segmento A'), ('Segmento B', 'El vehículo pertenece al segmento B'), ('Segmento C', 'El vehículo pertenece al segmento C'), ('Segmento D', 'El vehículo pertenece al segmento D'), ('Segmento E', 'El vehículo pertenece al segmento E')], default='Segmento A', max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Tabla_test',
        ),
    ]
